/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.jdw.trixieslimselfref

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.jdw.trixieslimselfref.subcommands.Cron

class Cli: CliktCommand(name="cli.sh") {
    val verbose by option("-v", "--verbose", help="Verbose output (default: false).").flag()

    override fun run() {
        Glob.verbose = verbose
    }
}


fun main(args: Array<String>)  {
    Cli()
        .subcommands(Cron())
        .main(args)
}


