/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.jdw.trixieslimselfref

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.jdw.trixieslimselfref.subcommands.upstream.Upstream
import com.github.jdw.trixieslimselfref.subcommands.general.General
import com.github.jdw.trixieslimselfref.subcommands.git.Git

class Main: CliktCommand(
    name="trixie-slim-selfref",
    printHelpOnEmptyArgs = true,
    help = """ A CLI tool with the purpose of building a Docker image based on debian:trixie-slim that can build itself - Much wow!
        
             Please peruse the README.md through the 🫡 general setting or visit github.com/jdw/trixie-slim-selfref for more!
            
            --- 🫶 Happy hacking! ⌨️ ---""") {
    val verbose by option("-v", "--verbose", help="Verbose output").flag()

    override fun run() {
        Glob.verbose = verbose
    }
}


fun main(args: Array<String>)  {
    Main()
        .subcommands(Upstream(), General(), Git())
        .main(args)
}


