/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */

pluginManagement {
    plugins {
        val kotlinVersion: String by settings
        val foojayVersion: String by settings

        id("org.jetbrains.kotlin.jvm") version kotlinVersion
        kotlin("plugin.serialization") version kotlinVersion
        id("org.gradle.toolchains.foojay-resolver-convention") version foojayVersion
    }
}

rootProject.name = "trixie-slim-selfref"
include("cli")
